# Generated by Django 3.0.6 on 2021-06-18 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job1', '0003_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
    ]
