# Generated by Django 3.0.6 on 2021-06-18 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job1', '0004_remove_job_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job1.Recruiter'),
        ),
    ]
