# Generated by Django 3.0.6 on 2021-06-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job1', '0006_remove_job_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
